version: "3.7"

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app-container
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www